
package ru.korusconsulting.medical;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "transfusionMedicalService", targetNamespace = "http://www.korusconsulting.ru")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransfusionMedicalService {


    /**
     * 
     * @param patientCredentials
     * @param orderInformation
     * @return
     *     returns ru.korusconsulting.medical.OrderResult
     */
    @WebMethod(action = "urn:orderBloodComponents")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orderBloodComponents", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.medical.OrderBloodComponents")
    @ResponseWrapper(localName = "orderBloodComponentsResponse", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.medical.OrderBloodComponentsResponse")
    @Action(input = "urn:orderBloodComponents", output = "http://www.korusconsulting.ru/transfusionMedicalService/orderBloodComponentsResponse")
    public OrderResult orderBloodComponents(
        @WebParam(name = "patientCredentials", targetNamespace = "")
        PatientCredentials patientCredentials,
        @WebParam(name = "orderInformation", targetNamespace = "")
        OrderInformation orderInformation);

    /**
     * 
     * @param donorInfo
     * @param patientCredentials
     * @param procedureInfo
     * @return
     *     returns ru.korusconsulting.medical.OrderResult
     */
    @WebMethod(action = "urn:orderMedicalProcedure")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orderMedicalProcedure", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.medical.OrderMedicalProcedure")
    @ResponseWrapper(localName = "orderMedicalProcedureResponse", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.medical.OrderMedicalProcedureResponse")
    @Action(input = "urn:orderMedicalProcedure", output = "http://www.korusconsulting.ru/transfusionMedicalService/orderMedicalProcedureResponse")
    public OrderResult orderMedicalProcedure(
        @WebParam(name = "donorInfo", targetNamespace = "")
        DonorInfo donorInfo,
        @WebParam(name = "patientCredentials", targetNamespace = "")
        PatientCredentials patientCredentials,
        @WebParam(name = "procedureInfo", targetNamespace = "")
        ProcedureInfo procedureInfo);

    /**
     * 
     * @return
     *     returns java.util.List<ru.korusconsulting.medical.ProcedureType>
     */
    @WebMethod(action = "urn:getProcedureTypes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcedureTypes", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.medical.GetProcedureTypes")
    @ResponseWrapper(localName = "getProcedureTypesResponse", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.medical.GetProcedureTypesResponse")
    @Action(input = "urn:getProcedureTypes", output = "http://www.korusconsulting.ru/transfusionMedicalService/getProcedureTypesResponse")
    public List<ProcedureType> getProcedureTypes();

    /**
     * 
     * @return
     *     returns java.util.List<ru.korusconsulting.medical.LaboratoryMeasureType>
     */
    @WebMethod(action = "urn:getLaboratoryMeasureTypes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLaboratoryMeasureTypes", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.medical.GetLaboratoryMeasureTypes")
    @ResponseWrapper(localName = "getLaboratoryMeasureTypesResponse", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.medical.GetLaboratoryMeasureTypesResponse")
    @Action(input = "urn:getLaboratoryMeasureTypes", output = "http://www.korusconsulting.ru/transfusionMedicalService/getLaboratoryMeasureTypesResponse")
    public List<LaboratoryMeasureType> getLaboratoryMeasureTypes();

    /**
     * 
     * @return
     *     returns java.util.List<ru.korusconsulting.medical.ComponentType>
     */
    @WebMethod(action = "urn:getComponentTypes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponentTypes", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.medical.GetComponentTypes")
    @ResponseWrapper(localName = "getComponentTypesResponse", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.medical.GetComponentTypesResponse")
    @Action(input = "urn:getComponentTypes", output = "http://www.korusconsulting.ru/transfusionMedicalService/getComponentTypesResponse")
    public List<ComponentType> getComponentTypes();

}
