
package misexchange;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.hl7.v3.MCCIIN000002UV01;
import org.hl7.v3.POCDMT000040LabeledDrug;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MISExchangePortType", targetNamespace = "MISExchange")
@XmlSeeAlso({
    misexchange.ObjectFactory.class,
    org.hl7.v3.ObjectFactory.class
})
public interface MISExchangePortType {


    /**
     * 
     * @param organizationRef
     * @param drug
     * @return
     *     returns misexchange.BalanceOfGoods
     */
    @WebMethod(operationName = "BalanceOfGoodsInOrganization", action = "MISExchange#MISExchange:BalanceOfGoodsInOrganization")
    @WebResult(targetNamespace = "MISExchange")
    @RequestWrapper(localName = "BalanceOfGoodsInOrganization", targetNamespace = "MISExchange", className = "misexchange.BalanceOfGoodsInOrganization")
    @ResponseWrapper(localName = "BalanceOfGoodsInOrganizationResponse", targetNamespace = "MISExchange", className = "misexchange.BalanceOfGoodsInOrganizationResponse")
    public BalanceOfGoods balanceOfGoodsInOrganization(
        @WebParam(name = "Drug", targetNamespace = "MISExchange")
        POCDMT000040LabeledDrug drug,
        @WebParam(name = "OrganizationRef", targetNamespace = "MISExchange")
        String organizationRef);

    /**
     * 
     * @param organizationRef
     * @param storageRef
     * @param drug
     * @return
     *     returns misexchange.BalanceOfGoods
     */
    @WebMethod(operationName = "BalanceOfGoodsInStorage", action = "MISExchange#MISExchange:BalanceOfGoodsInStorage")
    @WebResult(targetNamespace = "MISExchange")
    @RequestWrapper(localName = "BalanceOfGoodsInStorage", targetNamespace = "MISExchange", className = "misexchange.BalanceOfGoodsInStorage")
    @ResponseWrapper(localName = "BalanceOfGoodsInStorageResponse", targetNamespace = "MISExchange", className = "misexchange.BalanceOfGoodsInStorageResponse")
    public BalanceOfGoods balanceOfGoodsInStorage(
        @WebParam(name = "Drug", targetNamespace = "MISExchange")
        POCDMT000040LabeledDrug drug,
        @WebParam(name = "OrganizationRef", targetNamespace = "MISExchange")
        String organizationRef,
        @WebParam(name = "StorageRef", targetNamespace = "MISExchange")
        String storageRef);

    /**
     * 
     * @param organizationRef
     * @return
     *     returns misexchange.DepartmentList
     */
    @WebMethod(operationName = "GetDepartmentList", action = "MISExchange#MISExchange:GetDepartmentList")
    @WebResult(targetNamespace = "MISExchange")
    @RequestWrapper(localName = "GetDepartmentList", targetNamespace = "MISExchange", className = "misexchange.GetDepartmentList")
    @ResponseWrapper(localName = "GetDepartmentListResponse", targetNamespace = "MISExchange", className = "misexchange.GetDepartmentListResponse")
    public DepartmentList getDepartmentList(
        @WebParam(name = "OrganizationRef", targetNamespace = "MISExchange")
        String organizationRef);

    /**
     * 
     * @return
     *     returns misexchange.DrugList
     */
    @WebMethod(operationName = "GetDrugList", action = "MISExchange#MISExchange:GetDrugList")
    @WebResult(targetNamespace = "MISExchange")
    @RequestWrapper(localName = "GetDrugList", targetNamespace = "MISExchange", className = "misexchange.GetDrugList")
    @ResponseWrapper(localName = "GetDrugListResponse", targetNamespace = "MISExchange", className = "misexchange.GetDrugListResponse")
    public DrugList getDrugList();

    /**
     * 
     * @return
     *     returns misexchange.OrganizationList
     */
    @WebMethod(operationName = "GetOrganizationList", action = "MISExchange#MISExchange:GetOrganizationList")
    @WebResult(targetNamespace = "MISExchange")
    @RequestWrapper(localName = "GetOrganizationList", targetNamespace = "MISExchange", className = "misexchange.GetOrganizationList")
    @ResponseWrapper(localName = "GetOrganizationListResponse", targetNamespace = "MISExchange", className = "misexchange.GetOrganizationListResponse")
    public OrganizationList getOrganizationList();

    /**
     * 
     * @return
     *     returns misexchange.StorageList
     */
    @WebMethod(operationName = "GetStorageList", action = "MISExchange#MISExchange:GetStorageList")
    @WebResult(targetNamespace = "MISExchange")
    @RequestWrapper(localName = "GetStorageList", targetNamespace = "MISExchange", className = "misexchange.GetStorageList")
    @ResponseWrapper(localName = "GetStorageListResponse", targetNamespace = "MISExchange", className = "misexchange.GetStorageListResponse")
    public StorageList getStorageList();

    /**
     * 
     * @param request
     * @return
     *     returns org.hl7.v3.MCCIIN000002UV01
     */
    @WebMethod(operationName = "ProcessHL7v3Message", action = "MISExchange#MISExchange:ProcessHL7v3Message")
    @WebResult(targetNamespace = "MISExchange")
    @RequestWrapper(localName = "ProcessHL7v3Message", targetNamespace = "MISExchange", className = "misexchange.ProcessHL7V3Message")
    @ResponseWrapper(localName = "ProcessHL7v3MessageResponse", targetNamespace = "MISExchange", className = "misexchange.ProcessHL7V3MessageResponse")
    public MCCIIN000002UV01 processHL7V3Message(
        @WebParam(name = "Request", targetNamespace = "MISExchange")
        Request request);

}
