
package ru.korusconsulting.laboratory;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "trfu-laboratory-integration", targetNamespace = "http://www.korusconsulting.ru")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrfuLaboratoryIntegration {


    /**
     * 
     * @param results
     * @param biomaterialDefects
     * @param resultDoctorLisId
     * @param orderId
     * @param orderBarCode
     * @return
     *     returns java.lang.String
     * @throws ru.korusconsulting.laboratory.Exception_Exception
     */
    @WebMethod(action = "urn:setAnalysisResults")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setAnalysisResults", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.laboratory.SetAnalysisResults")
    @ResponseWrapper(localName = "setAnalysisResultsResponse", targetNamespace = "http://www.korusconsulting.ru", className = "ru.korusconsulting.laboratory.SetAnalysisResultsResponse")
    @Action(input = "urn:setAnalysisResults", output = "http://www.korusconsulting.ru/trfu-laboratory-integration/setAnalysisResultsResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://www.korusconsulting.ru/trfu-laboratory-integration/setAnalysisResults/Fault/Exception")
    })
    public String setAnalysisResults(
            @WebParam(name = "orderId", targetNamespace = "")
            int orderId,
            @WebParam(name = "orderBarCode", targetNamespace = "")
            String orderBarCode,
            @WebParam(name = "results", targetNamespace = "")
            List<AnalysisResult> results,
            @WebParam(name = "biomaterialDefects", targetNamespace = "")
            String biomaterialDefects,
            @WebParam(name = "resultDoctorLisId", targetNamespace = "")
            int resultDoctorLisId)
        throws Exception_Exception
    ;

}
